### ISSUE TITLE
Failed to open stream

### ISSUE THREAD

**Issue by hartenthaler** [Tywed/telegram#5]
I installed your module on my test system. Testing the link http://ahnentest.hartenthaler.eu/index.php?route=/cron/telegram results in an error:

> file_get_contents(https://api.telegram.org/bot7620748118:AAHJ4alZo5TKPkEWa_pCdmoc5fjDUQNWyKE/sendMessage): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
>  …/modules_v4/telegram/CronJob.php:244
> #0 [internal function]: Fisharebest\Webtrees\Http\Middleware\ErrorHandler->errorHandler()
> #1 …/modules_v4/telegram/CronJob.php(244): file_get_contents()
> #2 …/modules_v4/telegram/CronJob.php(87): Tywed\Webtrees\Module\Telegram\CronJob->sendTelegramMessage()
> #3 …/app/Http/Middleware/RequestHandler.php(52): Tywed\Webtrees\Module\Telegram\CronJob->handle()

**Comment by Tywed** [comment]
The API key needs to be reissued because it is compromised. Did you use a custom start and end of the message?

**Comment by hartenthaler** [comment]
Ok, I will use a new API key. No there is no start or end message. This test site uses HTTP and Pretty URL is  not activated.

**Comment by Tywed** [comment]
During testing, I'll just comment out this part in CronJob.php:

if ($startJd == $launch) {
            return response([
                'success' => false,
                'error' => 'The cron has already been launched today',
            ]);
        }

And in webtrees itself, I edit the dates for different events to the current date so that they are displayed in the “On this day” module
